"""Back-compat shim. Prefer ``autobench.audit.ahe``."""

from autobench.audit.ahe import (  # noqa: F401
    LiveRefutationStatus,
    PlannedCompaction,
    Prediction,
    PredictionVerification,
    _register_ahe_invalidation,
    ahe_scope_key,
    clip_prediction_to_feasible,
    compact_predictions,
    invalidate_prior_predictions,
    normalize_text,
    parse_prediction_from_llm_response,
    prediction_fingerprint,
    prediction_source_scope_key,
    prediction_to_dict,
    refute_live,
    should_emit_warning,
    verification_to_dict,
    verify_prediction,
)

__all__ = [
    "LiveRefutationStatus",
    "PlannedCompaction",
    "Prediction",
    "PredictionVerification",
    "clip_prediction_to_feasible",
    "compact_predictions",
    "invalidate_prior_predictions",
    "normalize_text",
    "parse_prediction_from_llm_response",
    "prediction_fingerprint",
    "prediction_source_scope_key",
    "prediction_to_dict",
    "refute_live",
    "should_emit_warning",
    "verification_to_dict",
    "verify_prediction",
]
