"""MiniMax worker agent for autobench — generates candidate code from prompts.

This module closes the single biggest architectural gap in autobench: the
evaluator previously defaulted ``generate_fn`` to ``lambda prompt, cfg: ""``,
meaning every benchmark case was scored against the empty string. With this
worker wired into ``run_first.py``, benchmark cases get real LLM-generated
code via the MiniMax OpenAI-compatible chat-completions endpoint.

The worker mirrors :class:`MiniMaxLLMWrapper` from ``minimax_improver.py`` in
its HTTP shape, retry/backoff discipline, and cost-tracking helpers. The
key difference: this worker is a *producer of code* (called per case),
whereas the improver is a *mutator of harness configs* (called per RSI
iteration). They share pricing, error handling, and observability patterns
but not the request schema or response parsing.

Wire shape::

    POST https://api.minimax.io/v1/chat/completions
    Authorization: Bearer $MINIMAX_API_KEY
    {
      "model": "MiniMax-M2.7",
      "messages": [
        {"role": "system", "content": "<harness.system_prompt or default>"},
        {"role": "user",   "content": "<case.prompt + harness.tool_surface>"}
      ],
      "temperature": 0.3,
      "max_tokens": <harness.budget["max_tokens"] or 4096>
    }

Failure model:
  1. Primary model (default ``MiniMax-M2.7``) is tried with ``max_retries``
     attempts using exponential backoff + Retry-After honouring.
  2. On total failure, the worker falls back to ``fallback_model``
     (default ``MiniMax-M2.5``) with the same retry budget.
  3. If both models fail, returns an empty code string (evaluator interprets
     this as a CE verdict; we do NOT raise so a single transient outage
     can't wedge the whole benchmark suite).
"""

from __future__ import annotations

import logging
import os
import random
import re
import statistics
import time
from collections import deque
from dataclasses import dataclass, field
from typing import Any

import httpx

from .core import HarnessConfig
from .observability import AutobenchObservability

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Billing unit — REQUESTS, not dollars.
# ---------------------------------------------------------------------------
# nervous-bus-dq7l: do NOT reintroduce a $/token rate table. The MiniMax
# coding plan bills by requests-per-5h (14250 cap), and any hardcoded
# $/token constant decays into a falsehood the moment list pricing shifts.
# Cost fields are retained on result dataclasses + observability events
# strictly as a backwards-compat shim and always carry 0.0. The unit that
# matters is the request count, threaded through as prompt_tokens /
# completion_tokens / latency_ms — the operator does any dollar math from
# an authoritative source, not from in-tree constants.


DEFAULT_SYSTEM_PROMPT = """You are a competitive programming agent.

You will receive a problem statement. Return ONLY a complete, self-contained
Python 3 program that reads from stdin and writes to stdout. No markdown
fences, no commentary, no explanation."""


# ---------------------------------------------------------------------------
# Result dataclass
# ---------------------------------------------------------------------------

@dataclass
class WorkerResult:
    """Outcome of a single MiniMaxWorker.generate() call.

    Attributes:
        code: Extracted code (markdown fences stripped, leading prose
            removed). Empty when both primary and fallback model failed.
        model_used: Which model actually produced the returned code —
            primary, fallback, or empty-on-total-failure.
        prompt_tokens: Tokens consumed in the prompt (sum across retries
            is NOT counted; this is the successful call's prompt only).
        completion_tokens: Tokens generated by the model.
        cost_usd: Always 0.0 — kept for downstream-schema compat only.
            See nervous-bus-dq7l: MiniMax bills by requests-per-5h, not $.
        latency_ms: Wall-clock latency from the start of generate() to
            successful response (or final failure).
        raw_response: Full raw content string from the LLM, useful for
            debugging fence-stripping and prose-stripping edge cases.
        error: Human-readable error description if total failure occurred,
            else None.
    """

    code: str = ""
    model_used: str = ""
    prompt_tokens: int = 0
    completion_tokens: int = 0
    cost_usd: float = 0.0
    latency_ms: float = 0.0
    raw_response: str = ""
    error: str | None = None

    def to_usage_dict(self) -> dict[str, Any]:
        """Return token + cost summary for aggregation in run_first.py."""
        return {
            "prompt_tokens": int(self.prompt_tokens),
            "completion_tokens": int(self.completion_tokens),
            "cost_usd": float(self.cost_usd),
            "model_used": self.model_used,
        }


# ---------------------------------------------------------------------------
# Worker class
# ---------------------------------------------------------------------------

class MiniMaxWorker:
    """Synchronous MiniMax-backed worker that generates code per case.

    The class implements both the explicit ``generate(prompt, harness)``
    method (returns :class:`WorkerResult`) and the ``__call__(prompt, cfg)``
    interface (returns just the ``code`` string) that ``BenchmarkEvaluator``
    expects as a ``generate_fn``.

    Args:
        model: Primary model name (default ``MiniMax-M2.7``).
        fallback_model: Used after primary exhausts retries (default
            ``MiniMax-M2.5``).
        api_key: MiniMax API key. Falls back to ``$MINIMAX_API_KEY``.
        temperature: Sampling temperature. MUST be in (0.0, 1.0].
        max_retries: Per-model retry budget (1s, 2s, 4s, ... base backoff).
        timeout_seconds: Per-request HTTP timeout. Default 240.0s.
            # 200s default: cf-7A A/B (tools/ab_minimax_hard_case.json) showed budget=1024 worst case 121s — gives 65s safety margin
            # 2026-05-17 nervous-bus-96k: bumped 200→240 after observing read-timeouts on M2.7 hard cases (session 01KRQTNMM8...). 65s margin retained over 121s p99.
            # Do NOT 'optimize' this back to 60s without re-running the A/B.
        base_url: Override for the API base URL (testing only).
        obs: Optional observability instance for emitting
            ``autobench.worker.v1`` events.
    """

    BASE_URL = "https://api.minimax.io"
    OPENAI_PATH = "/v1/chat/completions"
    ANTHROPIC_PATH = "/anthropic/v1/messages"

    def __init__(
        self,
        model: str = "MiniMax-M2.7",
        fallback_model: str = "MiniMax-M2.5",
        api_key: str | None = None,
        temperature: float = 0.3,
        max_retries: int = 3,
        timeout_seconds: float = 240.0,
        base_url: str | None = None,
        obs: AutobenchObservability | None = None,
        endpoint_mode: str = "anthropic",
        thinking_budget: int | None = 1024,
    ) -> None:
        """Construct a MiniMax worker.

        About ``thinking_budget`` (verified honoured against
        ``/anthropic/v1/messages`` 2026-05-16 via
        ``tools/check_minimax_thinking.py``): when set in ``"anthropic"``
        endpoint mode, attaches ``thinking={"type": "enabled",
        "budget_tokens": N}`` to the payload. This caps the *reasoning*
        block separately from the visible text output — the model can still
        produce its full code answer up to ``max_tokens`` after the budgeted
        reasoning. This is the right knob to pull on 60s timeouts: capping
        ``max_tokens`` truncates the *answer*, but a thinking budget
        truncates the explicit-CoT trace that dominates latency on
        easy/tier-1 problems.

        Defaults to 1024 — enough headroom for tier-1 Codeforces problems
        while keeping latency near the cf-1A 5-6s floor. Pass ``None`` to
        omit the field entirely (full reasoning, full ``max_tokens``).

        In ``"openai"`` endpoint mode the field is omitted regardless;
        the OpenAI-compat surface does not expose ``thinking``.
        """
        self.api_key = api_key or os.environ.get("MINIMAX_API_KEY", "")
        if not self.api_key:
            raise ValueError(
                "MINIMAX_API_KEY must be set or passed as api_key argument"
            )

        if not (0.0 < temperature <= 1.0):
            raise ValueError(
                f"MiniMax temperature must be in (0.0, 1.0], got {temperature}"
            )

        if endpoint_mode not in ("openai", "anthropic"):
            raise ValueError(
                f"endpoint_mode must be 'openai' or 'anthropic', got {endpoint_mode!r}"
            )

        # thinking_budget validation: None or a positive int. We can't yet
        # validate ``<= max_tokens`` here because max_tokens is per-call from
        # the harness budget — that check happens in _call_minimax.
        if thinking_budget is not None:
            if not isinstance(thinking_budget, int) or thinking_budget <= 0:
                raise ValueError(
                    "thinking_budget must be None or a positive int, "
                    f"got {thinking_budget!r}"
                )

        self.model = model
        self.fallback_model = fallback_model
        self.temperature = temperature
        self.max_retries = max_retries
        self.timeout_seconds = timeout_seconds
        self.base_url = (base_url or self.BASE_URL).rstrip("/")
        self.obs = obs
        self.endpoint_mode = endpoint_mode
        self.thinking_budget = thinking_budget

        # Persistent HTTP client — reused across all generate() calls so we
        # skip the TLS handshake on every request. ~200-500ms savings per
        # call against api.minimax.io. Closed in close() / __del__.
        self._http_client: httpx.Client | None = httpx.Client(
            timeout=self.timeout_seconds
        )

        # Class-level usage cache for run_first.py to read after each call.
        self._last_usage: dict[str, Any] = {
            "prompt_tokens": 0,
            "completion_tokens": 0,
            "cost_usd": 0.0,
            "model_used": "",
        }

        # --- Queue-pressure tracking (nervous-bus-8vn) ----------------------
        # Rolling window of (monotonic_timestamp, tokens_per_second, latency_ms)
        # tuples from the most recent successful generate() calls. Used to
        # detect MiniMax throughput degradation so an operator can tell
        # queue pressure apart from model reasoning length.
        self._qp_window: deque[tuple[float, float, float]] = deque(maxlen=5)
        # Median tokens/sec of the FIRST 3 successful calls in this worker's
        # lifetime. None until 3 calls have completed; never updates after.
        self._qp_baseline_tps: float | None = None
        # All (tps, latency_ms) samples observed in the first three calls,
        # used to compute baseline. Discarded once baseline is established.
        self._qp_first_calls: list[tuple[float, float]] = []
        # Monotonic timestamp of the last queue-pressure event emit. None
        # means "never emitted"; we use this to enforce the 30-second debounce.
        self._qp_last_emit_time: float | None = None
        # Rolling count of httpx.TimeoutException / TransportError retries
        # observed across the last 10 generate() calls. Each entry is the
        # number of timeouts seen during that one call.
        self._qp_timeout_history: deque[int] = deque(maxlen=10)
        # In-flight timeout counter for the current generate() call, reset
        # at the top of generate() and pushed onto _qp_timeout_history at
        # the end of generate(). Tracked even on total failure.
        self._qp_inflight_timeouts: int = 0

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def generate(
        self,
        prompt: str,
        harness: HarnessConfig,
        case_id: str = "",
    ) -> WorkerResult:
        """Generate code for one prompt+harness pair. Never raises.

        Args:
            prompt: The problem statement / case prompt.
            harness: HarnessConfig — provides system_prompt, tool_surface,
                and budget (max_tokens).
            case_id: Optional case identifier for observability emission.

        Returns:
            WorkerResult — ``.code`` is the extracted code or ``""`` on
            total failure.
        """
        start = time.monotonic()
        # Reset the per-call timeout counter at the top of every generate()
        # so _attempt_with_model can accumulate timeouts across retries and
        # across the primary→fallback hop within one logical call.
        self._qp_inflight_timeouts = 0
        system_msg = harness.system_prompt or DEFAULT_SYSTEM_PROMPT
        tool_surface = harness.tool_surface or ""
        user_msg = self._build_user_message(prompt, tool_surface)
        max_tokens = int(harness.budget.get("max_tokens", 4096) or 4096)

        # Primary attempt
        result = self._attempt_with_model(
            model=self.model,
            system_msg=system_msg,
            user_msg=user_msg,
            max_tokens=max_tokens,
            start_time=start,
            case_id=case_id,
        )
        if result.code or result.error is None:
            # Either we got code, or generate() succeeded but the model
            # returned an empty string (not a failure path — return as-is).
            if result.error is None:
                self._update_last_usage(result)
                self._emit_worker_event(case_id, result)
                self._record_call_for_queue_pressure(result)
                return result
            # Fall through if error is set even though code is empty.

        # Fallback attempt
        logger.warning(
            "MiniMaxWorker: primary model %s failed (%s); trying fallback %s",
            self.model,
            result.error,
            self.fallback_model,
        )
        fallback = self._attempt_with_model(
            model=self.fallback_model,
            system_msg=system_msg,
            user_msg=user_msg,
            max_tokens=max_tokens,
            start_time=start,
            case_id=case_id,
        )

        if fallback.error is None:
            self._update_last_usage(fallback)
            self._emit_worker_event(case_id, fallback)
            self._record_call_for_queue_pressure(fallback)
            return fallback

        # Both failed — return empty-code result, do NOT raise.
        logger.error(
            "MiniMaxWorker: fallback %s also failed (%s); returning empty code",
            self.fallback_model,
            fallback.error,
        )
        final = WorkerResult(
            code="",
            model_used=f"{self.model}+{self.fallback_model} (both failed)",
            prompt_tokens=0,
            completion_tokens=0,
            cost_usd=0.0,
            latency_ms=(time.monotonic() - start) * 1000.0,
            raw_response="",
            error=f"primary={result.error}; fallback={fallback.error}",
        )
        self._update_last_usage(final)
        self._emit_worker_event(case_id, final)
        # Total failure: still flush the timeout tally onto the rolling
        # history (so a streak of all-timeouts shows up in the next event)
        # but do not push a tps sample since none was produced.
        self._record_call_for_queue_pressure(final)
        return final

    def __call__(self, prompt: str, cfg: HarnessConfig) -> str:
        """Callable interface used by ``BenchmarkEvaluator.generate_fn``.

        Returns the code string only. Token / cost info is stashed on
        ``self._last_usage`` for the caller to read after the call.
        """
        result = self.generate(prompt, cfg)
        return result.code

    # ------------------------------------------------------------------
    # Internals
    # ------------------------------------------------------------------

    def _build_user_message(self, prompt: str, tool_surface: str) -> str:
        """Combine case prompt and tool surface description into one user msg."""
        if not tool_surface:
            return prompt
        return (
            f"{prompt}\n\n"
            f"--- TOOL SURFACE ---\n{tool_surface}\n"
            f"--- END TOOL SURFACE ---\n\n"
            f"Return ONLY the solution code (no markdown fences, no commentary)."
        )

    def _attempt_with_model(
        self,
        model: str,
        system_msg: str,
        user_msg: str,
        max_tokens: int,
        start_time: float,
        case_id: str,
    ) -> WorkerResult:
        """Try one model with full retry budget. Returns WorkerResult.

        On success: ``error=None`` and ``code`` populated (possibly empty
        if the model literally returned empty content — still success).
        On failure: ``error`` is a string, ``code=""``.
        """
        last_error: Exception | None = None
        for attempt in range(1, self.max_retries + 1):
            try:
                response_json = self._call_minimax(
                    model=model,
                    system_msg=system_msg,
                    user_msg=user_msg,
                    max_tokens=max_tokens,
                )
            except httpx.HTTPStatusError as e:
                last_error = e
                status = e.response.status_code if e.response is not None else 0
                if status != 429 and not (500 <= status < 600):
                    # Non-retriable — bail immediately.
                    return WorkerResult(
                        code="",
                        model_used=model,
                        latency_ms=(time.monotonic() - start_time) * 1000.0,
                        error=f"http_{status}: {e}",
                    )
                if attempt >= self.max_retries:
                    break
                backoff_ms = _calc_backoff_ms(attempt, e)
                logger.warning(
                    "MiniMaxWorker[%s]: HTTP %d on attempt %d/%d; retrying after %dms",
                    model, status, attempt, self.max_retries, backoff_ms,
                )
                time.sleep(backoff_ms / 1000.0)
                continue
            except (httpx.TimeoutException, httpx.TransportError) as e:
                last_error = e
                # Queue-pressure: tally this timeout/transport error for the
                # rolling 10-call window. The increment happens regardless of
                # whether we retry — every transient failure is a data point.
                self._qp_inflight_timeouts += 1
                if attempt >= self.max_retries:
                    break
                backoff_ms = _calc_backoff_ms(attempt, e)
                logger.warning(
                    "MiniMaxWorker[%s]: transport error on attempt %d/%d (%s); retrying after %dms",
                    model, attempt, self.max_retries, e, backoff_ms,
                )
                time.sleep(backoff_ms / 1000.0)
                continue

            # Got a response — parse it.
            try:
                raw_text, input_tokens, output_tokens = _parse_response(
                    response_json, self.endpoint_mode
                )
            except (KeyError, IndexError, TypeError) as exc:
                return WorkerResult(
                    code="",
                    model_used=model,
                    latency_ms=(time.monotonic() - start_time) * 1000.0,
                    error=f"malformed_response: {type(exc).__name__}: {exc}",
                )

            code = _extract_code(raw_text)
            latency_ms = (time.monotonic() - start_time) * 1000.0

            return WorkerResult(
                code=code,
                model_used=model,
                prompt_tokens=input_tokens,
                completion_tokens=output_tokens,
                cost_usd=0.0,  # nervous-bus-dq7l: never fabricate $ from tokens.
                latency_ms=latency_ms,
                raw_response=raw_text,
                error=None,
            )

        return WorkerResult(
            code="",
            model_used=model,
            latency_ms=(time.monotonic() - start_time) * 1000.0,
            error=f"retries_exhausted: {type(last_error).__name__}: {last_error}"
            if last_error is not None
            else "retries_exhausted: unknown",
        )

    def _call_minimax(
        self,
        model: str,
        system_msg: str,
        user_msg: str,
        max_tokens: int,
    ) -> dict[str, Any]:
        """Single HTTP POST to MiniMax. Branches on endpoint_mode.

        - ``"openai"``: POST /v1/chat/completions with OpenAI-shaped body.
          Thinking traces (if model emits them) are inlined into
          ``choices[0].message.content`` as ``<think>...</think>`` blocks.
        - ``"anthropic"``: POST /anthropic/v1/messages with Anthropic-shaped
          body. Thinking is serialised into its own content block of type
          ``"thinking"`` (separate from the ``"text"`` block carrying the
          code). This is the protocol-layer fix for the prose-leak CE bug.
        """
        if self.endpoint_mode == "anthropic":
            payload: dict[str, Any] = {
                "model": model,
                "system": system_msg,
                "messages": [{"role": "user", "content": user_msg}],
                "temperature": self.temperature,
                "max_tokens": max_tokens,
            }
            if self.thinking_budget is not None:
                # Defend against thinking_budget > max_tokens for this call —
                # the constructor accepts any positive int because max_tokens
                # is per-harness. If the budget would exceed available
                # output budget, clamp to max_tokens - 1 so the model still
                # has at least one token left for the visible answer.
                effective_budget = min(self.thinking_budget, max(1, max_tokens - 1))
                payload["thinking"] = {
                    "type": "enabled",
                    "budget_tokens": effective_budget,
                }
            url = f"{self.base_url}{self.ANTHROPIC_PATH}"
        else:
            payload = {
                "model": model,
                "messages": [
                    {"role": "system", "content": system_msg},
                    {"role": "user", "content": user_msg},
                ],
                "temperature": self.temperature,
                "max_tokens": max_tokens,
            }
            url = f"{self.base_url}{self.OPENAI_PATH}"

        headers = {
            "Authorization": f"Bearer {self.api_key}",
            "Content-Type": "application/json",
        }
        # Use the persistent client to avoid the per-call TLS handshake.
        # If it's been closed (post-__del__ in a leaked test, etc.), fall
        # back to a one-shot client so we never crash on a closed session.
        client = self._http_client
        if client is None:
            with httpx.Client(timeout=self.timeout_seconds) as fallback_client:
                resp = fallback_client.post(url, json=payload, headers=headers)
                resp.raise_for_status()
                return resp.json()
        resp = client.post(url, json=payload, headers=headers)
        resp.raise_for_status()
        return resp.json()

    # ------------------------------------------------------------------
    # Lifecycle
    # ------------------------------------------------------------------

    def close(self) -> None:
        """Release the persistent HTTP client. Safe to call multiple times."""
        client = self._http_client
        self._http_client = None
        if client is not None:
            try:
                client.close()
            except Exception:  # noqa: BLE001 — close is best-effort
                pass

    def __del__(self) -> None:  # pragma: no cover — GC timing dependent
        try:
            self.close()
        except Exception:  # noqa: BLE001
            pass

    def _update_last_usage(self, result: WorkerResult) -> None:
        self._last_usage = {
            "prompt_tokens": int(result.prompt_tokens),
            "completion_tokens": int(result.completion_tokens),
            "cost_usd": float(result.cost_usd),
            "model_used": result.model_used,
        }

    def _emit_worker_event(self, case_id: str, result: WorkerResult) -> None:
        """Forward to observability, if present. Never raises."""
        if self.obs is None:
            return
        try:
            self.obs.worker_call(
                case_id=case_id,
                model=result.model_used,
                prompt_tokens=int(result.prompt_tokens),
                completion_tokens=int(result.completion_tokens),
                cost_usd=float(result.cost_usd),
                latency_ms=float(result.latency_ms),
                code_preview=(result.code or "")[:512],
                error=result.error,
            )
        except Exception as e:  # noqa: BLE001
            logger.debug("MiniMaxWorker: obs emission failed (%s)", e)

    # ------------------------------------------------------------------
    # Queue-pressure tracking (nervous-bus-8vn)
    # ------------------------------------------------------------------

    def _record_call_for_queue_pressure(self, result: WorkerResult) -> None:
        """Update rolling state from one completed generate() call, then
        maybe emit ``autobench.worker.queue_pressure.v1``.

        - Always pushes the in-flight timeout count onto the 10-call history.
        - On a successful call (``error is None``), pushes a (ts, tps, latency)
          sample onto the 5-entry rolling window and updates / consults the
          baseline.
        - Emits a pressure event when either of:
              current_tps < 0.5 * baseline_tps
              latest_latency_ms > 2 * mean(window_latencies)
          ... and the 30s debounce window has elapsed since the last emit.
        """
        # Always record the timeout tally, even on total failure, so a
        # stretch of timeouts gets weight in subsequent decisions.
        self._qp_timeout_history.append(int(self._qp_inflight_timeouts))

        # No throughput sample to record if both models failed — bail.
        if result.error is not None:
            return
        # Cannot compute tps without positive latency and positive completion
        # tokens — skip silently.
        latency_ms = float(result.latency_ms or 0.0)
        completion_tokens = int(result.completion_tokens or 0)
        if latency_ms <= 0.0 or completion_tokens <= 0:
            return

        now = time.monotonic()
        current_tps = completion_tokens / (latency_ms / 1000.0)
        self._qp_window.append((now, current_tps, latency_ms))

        # Establish baseline from the first three successful calls.
        if self._qp_baseline_tps is None:
            self._qp_first_calls.append((current_tps, latency_ms))
            if len(self._qp_first_calls) >= 3:
                tps_samples = [t for t, _ in self._qp_first_calls[:3]]
                self._qp_baseline_tps = float(statistics.median(tps_samples))
                # Free the bootstrap buffer; we don't need it post-baseline.
                self._qp_first_calls = []
            # Baseline isn't valid yet — nothing to compare against.
            return

        baseline = self._qp_baseline_tps
        if baseline <= 0.0:
            # Degenerate baseline (the model produced zero-rate calls during
            # bootstrap). Don't emit — the deviation factor would be ill-defined.
            return

        # Pressure conditions.
        deviation_factor = current_tps / baseline
        window_latencies = [lat for _, _, lat in self._qp_window]
        mean_latency = (
            sum(window_latencies) / len(window_latencies)
            if window_latencies
            else 0.0
        )
        rate_pressure = deviation_factor < 0.5
        latency_pressure = (
            mean_latency > 0.0 and latency_ms > 2.0 * mean_latency
        )
        if not (rate_pressure or latency_pressure):
            return

        # Debounce: at most one event per 30 seconds.
        if (
            self._qp_last_emit_time is not None
            and (now - self._qp_last_emit_time) < 30.0
        ):
            return

        self._qp_last_emit_time = now

        if self.obs is None:
            return
        try:
            self.obs.worker_queue_pressure(
                model=self.model,
                current_rate_tps=float(current_tps),
                baseline_tps=float(baseline),
                deviation_factor=float(deviation_factor),
                recent_timeouts_count=int(sum(self._qp_timeout_history)),
                latest_latency_ms=float(latency_ms),
                window_size=int(len(self._qp_window)),
            )
        except Exception as e:  # noqa: BLE001
            logger.debug("MiniMaxWorker: queue_pressure emit failed (%s)", e)


# ---------------------------------------------------------------------------
# Helpers (module-level so tests can exercise them directly)
# ---------------------------------------------------------------------------

# Regex captures a fenced block: ``` optionally followed by a language tag,
# then a newline, then the body, then a closing ``` on its own line (or
# end-of-string).
_FENCED_RE = re.compile(
    r"```(?:[a-zA-Z0-9_+\-]*)\s*\n?(.*?)(?:\n```|```|\Z)",
    re.DOTALL,
)

# Strips <think>...</think> blocks that MiniMax-M2.7 sometimes emits even in
# the OpenAI-compatible response. The Anthropic-compatible endpoint serialises
# thinking into a separate content block of type "thinking", which _parse_response
# discards before reaching _extract_code — but this defensive strip catches the
# OpenAI path and any stray inline traces.
_THINK_BLOCK_RE = re.compile(
    r"<think>.*?(?:</think>|\Z)\s*",
    re.DOTALL | re.IGNORECASE,
)

# Leading prose patterns we strip when no fenced block is present. These are
# heuristics — the worker's system prompt asks for "no preamble", but real
# LLMs often inject one anyway.
_PROSE_PREFIX_RE = re.compile(
    r"^(?:here['']?s?\s+(?:the\s+)?(?:solution|code|answer)[:\s\.]*|"
    r"sure[!,\.]?\s+|"
    r"certainly[!,\.]?\s+|"
    r"i['']?ll\s+(?:provide|write|solve)[^\n]*\n)",
    re.IGNORECASE,
)


def _extract_code(raw_text: str) -> str:
    """Strip <think> blocks, markdown fences, and leading prose from an LLM response.

    Strategy:
        1. Strip any ``<think>...</think>`` (or unclosed ``<think>...EOF``)
           blocks first. The Anthropic endpoint normally prevents these from
           reaching us, but the OpenAI endpoint inlines them, and either
           endpoint can occasionally leak.
        2. If a fenced block is present (```python ... ``` or just ``` ... ```),
           return the body of the FIRST such block.
        3. Otherwise, strip a leading prose preamble like "Here's the
           solution:\n" and return the remainder.
        4. Always strip surrounding whitespace.
    """
    if not raw_text:
        return ""

    # Step 1: strip thinking traces.
    raw_text = _THINK_BLOCK_RE.sub("", raw_text)

    # Step 2: try fenced extraction.
    m = _FENCED_RE.search(raw_text)
    if m and m.group(1).strip():
        return m.group(1).strip()

    # Step 3: no fences — strip leading prose.
    stripped = _PROSE_PREFIX_RE.sub("", raw_text.lstrip(), count=1)
    return stripped.strip()


def _parse_response(
    response_json: dict[str, Any], endpoint_mode: str
) -> tuple[str, int, int]:
    """Parse a MiniMax response into ``(raw_text, input_tokens, output_tokens)``.

    Branches on ``endpoint_mode``:
      - ``"openai"``: ``choices[0].message.content`` is a string; usage has
        ``prompt_tokens`` / ``completion_tokens``.
      - ``"anthropic"``: ``content`` is a list of blocks like
        ``[{"type": "thinking", "thinking": "..."}, {"type": "text", "text": "..."}]``.
        We concatenate ONLY the ``"text"`` blocks — thinking blocks are
        deliberately discarded at parse time, not at extraction time, so the
        downstream ``_extract_code`` heuristics never see them. Usage carries
        ``input_tokens`` / ``output_tokens`` (no ``prompt_`` / ``completion_``
        prefix in Anthropic's schema).

    Raises:
        KeyError / IndexError / TypeError on malformed payloads — the caller
        wraps these into a WorkerResult.error string.
    """
    if endpoint_mode == "anthropic":
        blocks = response_json["content"]  # KeyError if missing
        text_parts: list[str] = []
        for block in blocks:
            if isinstance(block, dict) and block.get("type") == "text":
                text_parts.append(str(block.get("text", "")))
        raw_text = "".join(text_parts)
        usage = response_json.get("usage", {}) or {}
        input_tokens = int(usage.get("input_tokens", 0) or 0)
        output_tokens = int(usage.get("output_tokens", 0) or 0)
        return raw_text, input_tokens, output_tokens

    # openai
    raw_text = response_json["choices"][0]["message"]["content"]
    usage = response_json.get("usage", {}) or {}
    input_tokens = int(usage.get("prompt_tokens", 0) or 0)
    output_tokens = int(usage.get("completion_tokens", 0) or 0)
    return raw_text, input_tokens, output_tokens


def _calc_backoff_ms(attempt: int, error: Exception) -> int:
    """Exponential backoff (1s, 2s, 4s, ...) with ~20% jitter.

    Honours ``Retry-After`` header on ``httpx.HTTPStatusError`` when present.
    """
    base_ms = 1000 * (1 << (attempt - 1))
    jitter_ms = int(base_ms * 0.2 * random.random())
    total_ms = base_ms + jitter_ms

    resp = getattr(error, "response", None)
    if resp is not None and hasattr(resp, "headers"):
        retry_after = resp.headers.get("Retry-After")
        if retry_after:
            try:
                total_ms = int(float(retry_after)) * 1000
            except (ValueError, TypeError):
                pass

    return total_ms


def _estimate_cost(input_tokens: int, output_tokens: int, model: str) -> float:
    """REMOVED — see nervous-bus-dq7l.

    The MiniMax coding plan bills by requests-per-5h, not by tokens × $-rate.
    Any hardcoded pricing table is a fiction the moment list prices shift.
    This stub remains to avoid import errors at call sites that are being
    migrated; new code MUST NOT call this. Returns 0.0 unconditionally.
    """
    return 0.0
